Collider synchronization & visualization
altseed/Altseed2-csharp pull request #117
Opened 2020-07-10 08:25 UTC by Funny-Silkie

- コライダを親ノードに同期
- 視覚化ノードの定義

https://github.com/altseed/Altseed2/issues/458

2020-07-14 10:28 UTC, wraikny commented on Engine/Physics/ColliderNode/CircleColliderNode.cs
> +                ScaleCalcType.Min => Math.Min(scale.X, scale.Y),
絶対値が良いと思う(負の時に逆になってしまう)

2020-07-14 10:28 UTC, wraikny commented on Engine/Physics/ColliderNode/CircleColliderNode.cs
> +        public override Vector2F Size
sealed

2020-07-14 10:28 UTC, wraikny commented on Engine/Physics/ColliderNode/CircleColliderNode.cs
> +        public override void AdjustSize()
sealed

2020-07-14 10:28 UTC, wraikny commented on Engine/Physics/ColliderNode/ColliderNode.cs
> +        public override Matrix44F AbsoluteTransform => _absoluteTransform;
sealed

2020-07-14 10:28 UTC, wraikny commented on Engine/Physics/ColliderNode/ColliderVisualizeNode.cs
> +        public override Matrix44F AbsoluteTransform => RenderedPolygon.Transform;
sealed

2020-07-14 10:28 UTC, wraikny commented on Engine/Physics/ColliderNode/ColliderVisualizeNode.cs
> +    public class ColliderVisualizeNode : DrawnNode
デバッグ用でこれを継承して何かすることはないだろうし、sealed classにして良いのではないでしょうか

2020-07-14 10:28 UTC, wraikny commented on Engine/Physics/ColliderNode/ColliderVisualizeNode.cs
> +        public override Vector2F AnchorMax => base.AnchorMax;
sealedつけようと言いたいところだけど、親クラスの値をそのまま返すだけならoverrideする必要がないので、class自体をsealedにするなら消しちゃって良い。

2020-07-14 10:28 UTC, wraikny commented on Engine/Physics/ColliderNode/PolygonColliderNode.cs
> +        public override void AdjustSize()
sealed

2020-07-14 10:28 UTC, wraikny commented on Engine/Physics/ColliderNode/RectangleColliderNode.cs
> +        public override Vector2F Size
sealed

2020-07-14 10:28 UTC, wraikny commented
commentつけたつもりがpendingになってて今反映したので、ちょっと古いかも……あとでまた見ます

2020-07-21 02:02 UTC, wistnki requested changes
Circleのところにしかコメント付けてないけど、RectangleやPolygonも同様なのでそこも宜しく :pray:

2020-07-21 02:02 UTC, wistnki commented on Engine/Physics/ColliderNode/CircleColliderNode.cs
> +        internal const int VisualizerVertNum = 100;
CircleColliderVisualizerNodeに置く

2020-07-21 02:02 UTC, wistnki commented on Engine/Physics/ColliderNode/CircleColliderNode.cs
> +        internal CircleColliderNode(CircleCollider collider)
> public CircleColliderNode() : this(new CircleCollider()) { }
の実装にもなるし、
```
internal CircleColliderNode(CircleCollider collider = null)
{
    CircleCollider = collider ?? new CircleCollider();
```
がよさそう。

2020-07-21 02:02 UTC, wistnki commented on Engine/Physics/ColliderNode/ColliderNode.cs
> +        internal readonly static Color AreaColor = new Color(255, 100, 100, 100);
これもVisualizerのでは

2020-07-21 02:02 UTC, wistnki commented on Engine/Physics/ColliderNode/CircleColliderNode.cs
> +        internal sealed class CircleColliderVisualizeNode : ColliderVisualizeNode
クラス内クラスじゃなくて普通のクラスにしよう

2020-07-21 02:02 UTC, wistnki commented on Engine/Physics/ColliderNode/ColliderNode.cs
> +        public static ColliderVisualizeNode CreateVisualizeNode(ColliderNode colliderNode)
ColliderNode 側には Visualizer関連のものは置かない。
Transformに変更があるか検出するのに version を付けたりアクセス指定を緩めたりするのは、ないと出来ないと思うのでおｋ。

一つのメソッドがColliderNode を取って中でどのColliderかで分岐するのはとても良いので
> VisualizeNode.Create(ColliderNode colliderNode)
かなあ

2020-07-21 08:01 UTC, Funny-Silkie commented on Engine/Physics/ColliderNode/CircleColliderNode.cs
> +        internal const int VisualizerVertNum = 100;
修正しました

2020-07-21 08:03 UTC, Funny-Silkie commented on Engine/Physics/ColliderNode/CircleColliderNode.cs
> +        internal CircleColliderNode(CircleCollider collider)
確かにそうですね
publicのオーバーロードがあるので

```
public HogeColliderNode() : this(null) { }
internal HogeColliderNode(HogeCollider collider)
{
    HogeCollider = collider ?? new HogeCollider();
```
の方向で実装しました

2020-07-21 08:03 UTC, Funny-Silkie commented on Engine/Physics/ColliderNode/ColliderNode.cs
> +        internal readonly static Color AreaColor = new Color(255, 100, 100, 100);
失念しておりました
修正しました

2020-07-21 08:06 UTC, Funny-Silkie commented on Engine/Physics/ColliderNode/CircleColliderNode.cs
> +        internal sealed class CircleColliderVisualizeNode : ColliderVisualizeNode
versionはinternalにするまでも無いかなーと思いクラス内クラスにしていました
迷ったところですが，普通のクラスに直しました

2020-07-21 10:58 UTC, merged