Reduce allocation
altseed/Altseed2-csharp pull request #153
Opened 2020-08-10 07:40 UTC by wraikny

2020-08-10 15:21 UTC, gon6109 approved these changes

2020-08-10 16:17 UTC, wraikny commented
一旦rebaseします、Merge待ってください

2020-08-10 17:26 UTC, wistnki commented on Engine/Node/PolygonNode.cs
> +        public void SetVertexes(Span<Vertex> vertexes)
公開用にはIEumerable版もあったほうがよさそう。

2020-08-10 17:26 UTC, wistnki commented on Engine/Node/PolygonNode.cs
> +        public void SetVertexes(Span<Vector2F> vertexes, Color color)
同上

2020-08-10 17:27 UTC, wistnki requested changes
公開用のSet～メソッドはSpanだけじゃなくてIEumerableも
https://qiita.com/GlassGrass/items/cea3c6f91413c3582b5f#ilisttireadonlylistticollectiontienumerablet%E3%81%A7%E5%85%85%E5%88%86%E3%81%A7%E3%81%AF

2020-08-10 17:30 UTC, wistnki commented
内部でやりとりするやつが生配列だったりする部分をSpanで置き換えるのやstackallocを使うのはgood

2020-08-10 22:51 UTC, wraikny commented on Engine/Node/PolygonNode.cs
> +        public void SetVertexes(Span<Vertex> vertexes)
@wistnki `IReadOnlyCollection` で用意してます。IEnumerableだと要素数が事前に確定するとは限らないので、HogeArrayへの変換のために引きずるにとるのは不適切かつ、internalメソッドなのでそれでよいと思います

2020-08-10 22:54 UTC, wraikny commented on Engine/Node/PolygonNode.cs
> +        public void SetVertexes(Span<Vertex> vertexes)
@wistnki HogeArrayレベルでは IReadOnlyCollectionのメソッドを生やしていて、IEnumerableだと要素数が事前に確定するとは限らず場合によっては無駄が大きいからですが、ここのSetVertexesもIReadOnlyCollectionで良いですかね

2020-08-11 03:21 UTC, wraikny commented
HogeArrayもいちいち作り直さなくても、
var vs = renderedPolygon.Vertexes ?? VertexArray.Create(span.Length);
vs.FromSpan(span);
renderedPolygon.Vertexes = vs;
でいいのかな……？？

2020-08-11 03:24 UTC, wistnki commented on Engine/Node/PolygonNode.cs
> +        public void SetVertexes(Span<Vertex> vertexes)
最強汎用読み取り専用コレクションIEnumerableで取りあえずなんでも受け取って、
（指摘の通りの無駄を減らせるなら減らすために）
実は要素数持ってる型だった場合はダウンキャストして、その要素数を使った確保を行う、ということをしている。

2020-08-11 03:29 UTC, wistnki commented on Engine/Node/PolygonNode.cs
> +        public void SetVertexes(Span<Vertex> vertexes)
なのでもともとHogeArray自体がIEnumerableを食って上記の処理をおこなってたかと。
そこにSpanバージョンを生やすのかなと思っていた。

2020-08-11 23:41 UTC, wraikny commented
VertexArray/Vector2FArray自体のallocationも減らす変更をさらに加えています
08:32
_PolygonNode.Vertex.FromSpan(span);
_PolygonNode.Vertex = _PolygonNode.Vertex;
みたいなコードにしだだけですけど
08:33
また、Vector2FArrayでoverwriteする箇所のallocationも減らすために、EngineにVector2FArrayを1個持たせてそれを使うようにしました

2020-08-12 07:39 UTC, wistnki requested changes

2020-08-12 07:39 UTC, wistnki commented on Engine/Engine.cs
> +            CullingSystem.DrawingRenderedIds.CopyTo(_DrawingRenderedIdsBuffer);
DrawingRenderedIdsの個数の最大値はどうあがいてもRenderedCollectionが持ってるノードの個数までなので、
ここでリサイズするよりは最初から最大値確保しておいてよいのでは

2020-08-12 07:39 UTC, wistnki commented on Engine/Node/PolygonNode.cs
> +                _RequireCalcTransform = true;
_RequireCalcTransform は Transform(自身や親のPositionやAngleなど)に変化があった場合に使用する行列を更新するフラグ

2020-08-12 07:54 UTC, wraikny commented on Engine/Node/PolygonNode.cs
> +                _RequireCalcTransform = true;
@wistnki 今のmasterのコードが
```
/// <summary>
        /// 頂点情報のコレクションを取得または設定します。
        /// </summary>
        public IReadOnlyList<Vertex> Vertexes
        {
            get => _RenderedPolygon.Vertexes?.ToArray();
            set
            {
                var vertexArray = VertexArray.Create(value);
                _RenderedPolygon.Vertexes = vertexArray;

                _IsValid = Validate(vertexArray);
                _RequireCalcTransform = true;
            }
        }
```

なのは……？(rebaseの関係でifが混入してるのは消します

2020-08-12 08:05 UTC, wraikny commented on Engine/Engine.cs
> +            CullingSystem.DrawingRenderedIds.CopyTo(_DrawingRenderedIdsBuffer);
@wistnki 
`_DrawingRenderedIdsBuffer`は使いまわしています。
```
if (_DrawingRenderedIdsBuffer is null || _DrawingRenderedIdsBuffer.Length * 2 < cullingIdsCount)
            {
                _DrawingRenderedIdsBuffer = new int[cullingIdsCount];
            }
            else if (_DrawingRenderedIdsBuffer.Length < cullingIdsCount)
            {
                _DrawingRenderedIdsBuffer = new int[_DrawingRenderedIdsBuffer.Length * 2];
            }
```
で、長さが足りなくて、半分未満だった場合は`cullingIdsCount`だけ、半分以上だった場合は現在の長さの2倍確保してます。（もう少し改善できるかもしれないけど）

RenderedCollectionの数が大量かつほとんどがカリングされる場合（マップが広くてカメラで部分を切り取ると容易に発生する）は無駄が大きそうです。

2020-08-12 08:11 UTC, wraikny commented on Engine/Node/PolygonNode.cs
> +                _RequireCalcTransform = true;
@wistnki 
そもそも `_RequireCalcTransform` がかなりいろんなプロパティについていること自体がおかしそうな気がする

2020-08-12 08:12 UTC, wraikny commented on Engine/Node/PolygonNode.cs
> +                _RequireCalcTransform = true;
ので、別PRでまとめて直すべきかと思う

2020-08-12 10:48 UTC, wistnki commented on Engine/Engine.cs
> +            CullingSystem.DrawingRenderedIds.CopyTo(_DrawingRenderedIdsBuffer);
描画は直列にしか行えないので_DrawingRenderedIdsBufferを使いまわすのは全然おｋ

RenderedCollectionの個数だと結局描画ノードAddしまくったときヤバイというのもおけまる。

>半分未満だった場合はcullingIdsCountだけ、半分以上だった場合は現在の長さの2倍確保
単に、足りないなら現在の個数の2倍確保だとどうなんだろう。

とにかくクソデカ配列の再確保を減らしたい欲があるので、いい方法を模索したい。

2020-08-12 10:54 UTC, wistnki commented
@wraikny 
stackalloc してる箇所、スタックに積める大きさはそんなに大きくないので一定以上大きいサイズ確保を行う可能性があるところは、普通の配列にfallbackする処理が必要
https://ufcpp.net/blog/2018/12/spanify/

2020-08-12 10:58 UTC, wistnki commented on Engine/Node/PolygonNode.cs
> +                _RequireCalcTransform = true;
_RequireCalcTransformはその名の通りTransform行列の再計算が必要かどうかのフラグなので、
Transformに関するもの（Position, Angle, Scale, CenterPositionなどなど）についてるのは仕様では

2020-08-12 11:01 UTC, wistnki commented on Engine/Node/PolygonNode.cs
> +        /// 各頂点に指定した色を設定する
rebaseの影響か戻ってる

2020-08-12 11:01 UTC, wistnki commented on Engine/Node/PolygonNode.cs
> +                _RequireCalcTransform = true;
とりあえず、
>rebaseの関係でifが混入してるのは消します
だけでよさそう

2020-08-12 12:11 UTC, wraikny commented on Engine/Node/PolygonNode.cs
> +                _RequireCalcTransform = true;
wistnki いや、TextureとかSrcにもついてる……

2020-08-12 12:12 UTC, wraikny commented
大きかったらArrayPoolか

2020-08-12 12:17 UTC, wraikny commented
http://ikorin2.hatenablog.jp/entry/2020/07/25/113904

2020-08-12 12:35 UTC, wraikny commented on Engine/Engine.cs
> +            CullingSystem.DrawingRenderedIds.CopyTo(_DrawingRenderedIdsBuffer);
ArrayPool使います

2020-08-12 13:20 UTC, wraikny commented
@wistnki stackallocかArrayPoolかの分岐でdiffが結構最悪になってしまった（FileViewを横に並べるといいかも）のですが、修正（とMatrixでstackalloc使ってなかったのを使うように追加）したのでよろです。

2020-08-13 07:00 UTC, wistnki approved these changes

2020-08-14 05:15 UTC, merged