Auto Collision System
altseed/Altseed2-csharp pull request #76
Opened 2020-04-18 15:08 UTC by Funny-Silkie

・自動でコレクションに追加/削除
・衝突開始/継続/終了をイベント感知
・コレクション処理はSlackにあった関係でのみ実行

2020-04-18 19:37 UTC, wistnki requested changes

2020-04-18 19:37 UTC, wistnki commented on Engine/Collection/RegisterableCollection.cs
> -        private readonly List<TElement> CurrentCollection = new List<TElement>();
親子関係の構築は RegisterableCollection に隠ぺいされているのでこの辺りを RegisterableCollection から触る機会はないはず

2020-04-18 19:37 UTC, wistnki commented on Engine/CorePartial/Collider.cs
> +        public ColliderNode Owner { get; internal set; }
不要かと（ColliderNodeのコンストラクタ参照）

2020-04-18 19:37 UTC, wistnki commented on Engine/Node/Node.cs
> +            if (node is CollisionManagerNode && ContainsCollisionManager()) throw new InvalidOperationException("既に衝突判定マネージャが格納されており，追加する事が出来ません");
このチェックは CollisionManagerNode の Registered メソッドで
ContainsCollisionManager() にしてもそうだけど、なるべく派生クラスに関する実装は書かないほうがいいので

2020-04-18 19:37 UTC, wistnki commented on Engine/Physics/ColliderNode.cs
> +        public Collider Collider
ColliderNode を生成した時点でCollider も自動生成すればいいかと。
つけても getter だけ

2020-04-18 19:37 UTC, wistnki commented on Engine/Node/Node.cs
> +                foreach (var current in _Children.AddQueue)
CollisionNode、CollisionManagerNode 双方の Added のなかでお互いに接続する処理はしてるのでわざわざ AddQueue まで見に行く必要はないかと

2020-04-18 19:37 UTC, wistnki commented on Engine/Physics/CollisionInfo.cs
> +        public Collider SelfCollider { get; }
そのコライダノードを持ってるノードのほうがよさそう

2020-04-18 19:37 UTC, wistnki commented on Engine/Physics/CollisionCollection.cs
> +                            else if (nowColliding) receiver2.OnCollisionEnter(new CollisionInfo(comparison.Collider, current.Collider, CollisionType.Enter));
current.Parent と comparison.Parent に対して同じことをしているのでメソッドに切り出すなどするとよさそう

2020-04-18 19:37 UTC, wistnki commented on Engine/Physics/CollisionCollection.cs
> +        internal struct Enumerator : IEnumerator<ColliderNode>
https://ufcpp.net/study/csharp/sp2_iterator.html#GetEnum
みたく yield return するメソッドでよい気もする

2020-04-19 03:03 UTC, Funny-Silkie commented on Engine/Physics/CollisionCollection.cs
> +        internal struct Enumerator : IEnumerator<ColliderNode>
これイテレータ使うか迷ったんですが，シリアライズ対応のために一応こういう形にしました

2020-04-19 04:46 UTC, wistnki commented on Engine/Physics/ColliderNode.cs
> +            Collider = collider ?? throw new ArgumentNullException(nameof(collider), "引数がnullです");
ここでコライダの生成もやってしまおうという（つまりColliderごとの派生クラスは要る）

2020-04-22 12:37 UTC, merged